export const USER_GET_CATEGORIES = 'USER_GET_CATEGORIES';
export const SERVER_GET_CATEGORIES_SUCCESS = 'SERVER_GET_CATEGORIES_SUCCESS';
export const SERVER_GET_CATEGORIES_ERROR = 'SERVER_GET_CATEGORIES_ERROR';