export const USER_GET_EMPLOYEES = 'USER_GET_EMPLOYEES';
export const SERVER_GET_EMPLOYEES_SUCCESS = 'SERVER_GET_EMPLOYEES_SUCCESS';
export const SERVER_GET_EMPLOYEES_ERROR = 'SERVER_GET_EMPLOYEES_ERROR';

export const USER_ADD_EMPLOYEE = 'USER_ADD_EMPLOYEE';
export const SERVER_ADD_EMPLOYEE_INVALID = 'SERVER_ADD_EMPLOYEE_INVALID';
export const SERVER_ADD_EMPLOYEE_SUCCESS = 'SERVER_ADD_EMPLOYEE_SUCCESS';
export const SERVER_ADD_EMPLOYEE_ERROR = 'SERVER_ADD_EMPLOYEE_ERROR';
export const ADD_EMPLOYEE_TIMER_ENDS = 'ADD_EMPLOYEE_TIMER_ENDS';

export const USER_UPDATE_EMPLOYEE = 'USER_UPDATE_EMPLOYEE';
export const SERVER_UPDATE_EMPLOYEE_INVALID = 'SERVER_UPDATE_EMPLOYEE_INVALID';
export const SERVER_UPDATE_EMPLOYEE_SUCCESS = 'SERVER_UPDATE_EMPLOYEE_SUCCESS';
export const SERVER_UPDATE_EMPLOYEE_ERROR = 'SERVER_UPDATE_EMPLOYEE_ERROR';
export const UPDATE_EMPLOYEE_TIMER_ENDS = 'UPDATE_EMPLOYEE_TIMER_ENDS';

export const USER_UPDATE_EMPLOYEE_IS_DISABLED = 'USER_UPDATE_EMPLOYEE_IS_DISABLED';
export const SERVER_UPDATE_EMPLOYEE_IS_DISABLED_SUCCESS = 'SERVER_UPDATE_EMPLOYEE_IS_DISABLED_SUCCESS';
export const SERVER_UPDATE_EMPLOYEE_IS_DISABLED_ERROR = 'SERVER_UPDATE_EMPLOYEE_IS_DISABLED_ERROR';

export const USER_GET_ROLES = 'USER_GET_ROLES';
export const SERVER_GET_ROLES_SUCCESS = 'SERVER_GET_ROLES_SUCCESS';
export const SERVER_GET_ROLES_ERROR = 'SERVER_GET_ROLES_ERROR';

export const USER_OPENS_CREATE_EMPLOYEE_FORM = 'USER_OPENS_CREATE_EMPLOYEE_FORM';
export const USER_CLOSES_CREATE_EMPLOYEE_FORM = 'USER_CLOSES_CREATE_EMPLOYEE_FORM';