export const USER_UPDATE_PASSWORD = 'USER_UPDATE_PASSWORD';
export const SERVER_UPDATE_PASSWORD_INVALID = 'SERVER_UPDATE_PASSWORD_INVALID';
export const SERVER_UPDATE_PASSWORD_SUCCESS = 'SERVER_UPDATE_PASSWORD_SUCCESS';
export const SERVER_UPDATE_PASSWORD_ERROR = 'SERVER_UPDATE_PASSWORD_ERROR';
export const UPDATE_PASSWORD_TIMER_ENDS = 'UPDATE_PASSWORD_TIMER_ENDS';

export const USER_GET_EMPLOYEE_DETAILS = 'USER_GET_EMPLOYEE_DETAILS';
export const SERVER_GET_EMPLOYEE_DETAILS_SUCCESS = 'SERVER_GET_EMPLOYEE_DETAILS_SUCCESS';
export const SERVER_GET_EMPLOYEE_DETAILS_ERROR = 'SERVER_GET_EMPLOYEE_DETAILS_ERROR';

export const USER_FIRST_NAME_CHANGE = 'USER_FIRST_NAME_CHANGE';
export const USER_LAST_NAME_CHANGE = 'USER_LAST_NAME_CHANGE';
export const USER_USER_NAME_CHANGE = 'USER_USER_NAME_CHANGE';

export const USER_UPDATE_EMPLOYEE_DETAILS = 'USER_UPDATE_EMPLOYEE_DETAILS';
export const SERVER_UPDATE_EMPLOYEE_DETAILS_INVALID = 'SERVER_UPDATE_EMPLOYEE_DETAILS_INVALID';
export const SERVER_UPDATE_EMPLOYEE_DETAILS_SUCCESS = 'SERVER_UPDATE_EMPLOYEE_DETAILS_SUCCESS';
export const SERVER_UPDATE_EMPLOYEE_DETAILS_ERROR = 'SERVER_UPDATE_EMPLOYEE_DETAILS_ERROR';
export const UPDATE_EMPLOYEE_DETAILS_TIMER_ENDS = 'UPDATE_EMPLOYEE_DETAILS_TIMER_ENDS';