export const USER_GET_HTML_PAGES = 'USER_GET_HTML_PAGES';
export const SERVER_GET_HTML_PAGES_SUCCESS = 'SERVER_GET_HTML_PAGES_SUCCESS';
export const SERVER_GET_HTML_PAGES_ERROR = 'SERVER_GET_HTML_PAGES_ERROR';

export const USER_GET_HTML_PAGE = 'USER_GET_HTML_PAGE';
export const SERVER_GET_HTML_PAGE_SUCCESS = 'SERVER_GET_HTML_PAGE_SUCCESS';
export const SERVER_GET_HTML_PAGE_ERROR = 'SERVER_GET_HTML_PAGE_ERROR';

export const USER_UPDATE_HTML_PAGE_TITLE = 'USER_UPDATE_HTML_PAGE_TITLE';
export const USER_UPDATE_HTML_PAGE_META_DESCRIPTION = 'USER_UPDATE_HTML_PAGE_META_DESCRIPTION';
export const USER_UPDATE_HTML_PAGE_META_KEYWORDS = 'USER_UPDATE_HTML_PAGE_META_KEYWORDS';
export const USER_UPDATE_HTML_PAGE_CONTENT = 'USER_UPDATE_HTML_PAGE_CONTENT';

export const USER_UPDATE_HTML_PAGE = 'USER_UPDATE_HTML_PAGE';
export const SERVER_UPDATE_HTML_PAGE_INVALID = 'SERVER_UPDATE_HTML_PAGE_INVALID';
export const SERVER_UPDATE_HTML_PAGE_SUCCESS = 'SERVER_UPDATE_HTML_PAGE_SUCCESS';
export const SERVER_UPDATE_HTML_PAGE_ERROR = 'SERVER_UPDATE_HTML_PAGE_ERROR';
export const UPDATE_HTML_PAGE_TIMER_ENDS = 'UPDATE_HTML_PAGE_TIMER_ENDS';

export const USER_ADD_HTML_PAGE = 'USER_ADD_HTML_PAGE';
export const SERVER_ADD_HTML_PAGE_INVALID = 'SERVER_ADD_HTML_PAGE_INVALID';
export const SERVER_ADD_HTML_PAGE_SUCCESS = 'SERVER_ADD_HTML_PAGE_SUCCESS';
export const SERVER_ADD_HTML_PAGE_ERROR = 'SERVER_ADD_HTML_PAGE_ERROR';
export const ADD_HTML_PAGE_TIMER_ENDS = 'ADD_HTML_PAGE_TIMER_ENDS';

export const USER_GET_HTML_PAGE_TYPES = 'GET_HTML_PAGE_TYPES';
export const SERVER_GET_HTML_PAGE_TYPES_SUCCESS = 'SERVER_GET_HTML_PAGE_TYPES_SUCCESS';
export const SERVER_GET_HTML_PAGE_TYPES_ERROR = 'SERVER_GET_HTML_PAGE_TYPES_ERROR';

export const USER_UPDATE_HTML_PAGE_PUBLISHED = 'USER_UPDATE_HTML_PAGE_PUBLISHED';
export const SERVER_UPDATE_HTML_PAGE_PUBLISHED_SUCCESS = 'SERVER_UPDATE_HTML_PAGE_PUBLISHED_SUCCESS';
export const SERVER_UPDATE_HTML_PAGE_PUBLISHED_ERROR = 'SERVER_UPDATE_HTML_PAGE_PUBLISHED_ERROR';

export const USER_DELETE_HTML_PAGE = 'USER_DELETE_HTML_PAGE';
export const SERVER_DELETE_HTML_PAGE_SUCCESS = 'SERVER_DELETE_HTML_PAGE_SUCCESS';
export const SERVER_DELETE_HTML_PAGE_ERROR = 'SERVER_DELETE_HTML_PAGE_ERROR';
export const DELETE_HTML_PAGE_TIMER_ENDS = 'DELETE_HTML_PAGE_TIMER_ENDS';