export const USER_LOG_IN = 'USER_LOG_IN';

export const USER_LOG_IN_USER_NAME_CHANGE = 'USER_LOG_IN_USER_NAME_CHANGE';
export const USER_LOG_IN_PASSWORD_CHANGE = 'USER_LOG_IN_PASSWORD_CHANGE';

export const SERVER_LOG_IN_INVALID = 'SERVER_LOG_IN_INVALID';
export const SERVER_LOG_IN_SUCCESS = 'SERVER_LOG_IN_SUCCESS';
export const SERVER_LOG_IN_ERROR = 'SERVER_LOG_IN_ERROR';

export const LOG_IN_TIMER_ENDS = 'LOG_IN_TIMER_ENDS';