export const USER_GET_ARTICLES = 'USER_GET_ARTICLES';
export const SERVER_GET_ARTICLES_SUCCESS = 'SERVER_GET_ARTICLES_SUCCESS';
export const SERVER_GET_ARTICLES_ERROR = 'SERVER_GET_ARTICLES_ERROR';

export const USER_GET_ARTICLE = 'USER_GET_ARTICLE';
export const SERVER_GET_ARTICLE_SUCCESS = 'SERVER_GET_ARTICLE_SUCCESS';
export const SERVER_GET_ARTICLE_ERROR = 'SERVER_GET_ARTICLE_ERROR';

export const USER_UPDATE_ARTICLE = 'USER_UPDATE_ARTICLE';
export const SERVER_UPDATE_ARTICLE_INVALID = 'SERVER_UPDATE_ARTICLE_INVALID';
export const SERVER_UPDATE_ARTICLE_SUCCESS = 'SERVER_UPDATE_ARTICLE_SUCCESS';
export const SERVER_UPDATE_ARTICLE_ERROR = 'SERVER_UPDATE_ARTICLE_ERROR';
export const UPDATE_ARTICLE_TIMER_ENDS = 'UPDATE_ARTICLE_TIMER_ENDS';

export const USER_UPDATE_PUBLISH_DATE = 'USER_UPDATE_PUBLISH_DATE';
export const USER_UPDATE_TITLE = 'USER_UPDATE_TITLE';
export const USER_UPDATE_META_DESCRIPTION = 'USER_UPDATE_META_DESCRIPTION';
export const USER_UPDATE_CONTENT = 'USER_UPDATE_CONTENT';

export const USER_GET_CONTENT_PARENTS = 'USER_GET_CONTENT_PARENTS';
export const SERVER_GET_CONTENT_PARENTS_SUCCESS = 'SERVER_GET_CONTENT_PARENTS_SUCCESS';
export const SERVER_GET_CONTENT_PARENTS_ERROR = 'SERVER_GET_CONTENT_PARENTS_ERROR';
export const USER_GET_CONTENT_PARENT_TYPES = 'USER_GET_CONTENT_PARENT_TYPES';
export const SERVER_GET_CONTENT_PARENT_TYPES_SUCCESS = 'SERVER_GET_CONTENT_PARENT_TYPES_SUCCESS';
export const SERVER_GET_CONTENT_PARENT_TYPES_ERROR = 'SERVER_GET_CONTENT_PARENT_TYPES_ERROR';
export const USER_ADD_CONTENT_PARENT_TO_ARTICLE = 'USER_ADD_CONTENT_PARENT_TO_ARTICLE';
export const USER_DELETE_CONTENT_PARENT_FROM_ARTICLE = 'USER_DELETE_CONTENT_PARENT_FROM_ARTICLE';
export const USER_OPENS_CREATE_ARTICLE_PAGE = 'USER_OPENS_CREATE_ARTICLE_PAGE';

export const USER_UPDATE_ARTICLE_IS_DISABLED = 'USER_UPDATE_ARTICLE_IS_DISABLED';
export const SERVER_UPDATE_ARTICLE_IS_DISABLED_INVALID = 'SERVER_UPDATE_ARTICLE_IS_DISABLED_INVALID';
export const SERVER_UPDATE_ARTICLE_IS_DISABLED_SUCCESS = 'SERVER_UPDATE_ARTICLE_IS_DISABLED_SUCCESS';
export const SERVER_UPDATE_ARTICLE_IS_DISABLED_ERROR = 'SERVER_UPDATE_ARTICLE_IS_DISABLED_ERROR';
export const UPDATE_ARTICLE_IS_DISABLED_TIMER_ENDS = 'UPDATE_ARTICLE_IS_DISABLED_TIMER_ENDS';

export const USER_ADD_ARTICLE = 'USER_ADD_ARTICLE';
export const SERVER_ADD_ARTICLE_INVALID = 'SERVER_ADD_ARTICLE_INVALID';
export const SERVER_ADD_ARTICLE_SUCCESS = 'SERVER_ADD_ARTICLE_SUCCESS';
export const SERVER_ADD_ARTICLE_ERROR = 'SERVER_ADD_ARTICLE_ERROR';
export const ADD_ARTICLE_TIMER_ENDS = 'ADD_ARTICLE_TIMER_ENDS';

export const USER_UPDATE_ARTICLE_IMAGE = 'USER_UPDATE_ARTICLE_IMAGE';
export const SERVER_UPDATE_ARTICLE_IMAGE_INVALID = 'SERVER_UPDATE_ARTICLE_IMAGE_INVALID';
export const SERVER_UPDATE_ARTICLE_IMAGE_SUCCESS = 'SERVER_UPDATE_ARTICLE_IMAGE_SUCCESS';
export const SERVER_UPDATE_ARTICLE_IMAGE_ERROR = 'SERVER_UPDATE_ARTICLE_IMAGE_ERROR';
export const UPDATE_ARTICLE_IMAGE_TIMER_ENDS = 'UPDATE_ARTICLE_IMAGE_TIMER_ENDS';

export const USER_UPDATE_ARTICLE_BODY_IMAGE = 'USER_UPDATE_ARTICLE_BODY_IMAGE';
export const SERVER_UPDATE_ARTICLE_BODY_IMAGE_INVALID = 'SERVER_UPDATE_ARTICLE_BODY_IMAGE_INVALID';
export const SERVER_UPDATE_ARTICLE_BODY_IMAGE_INVALID_CALLBACK_COMPLETE = 'SERVER_UPDATE_ARTICLE_BODY_IMAGE_INVALID_CALLBACK_COMPLETE';
export const SERVER_UPDATE_ARTICLE_BODY_IMAGE_SUCCESS = 'SERVER_UPDATE_ARTICLE_BODY_IMAGE_SUCCESS';
export const SERVER_UPDATE_ARTICLE_BODY_IMAGE_SUCCESS_CALLBACK_COMPLETE = 'SERVER_UPDATE_ARTICLE_BODY_IMAGE_SUCCESS_CALLBACK_COMPLETE';
export const SERVER_UPDATE_ARTICLE_BODY_IMAGE_ERROR = 'SERVER_UPDATE_ARTICLE_BODY_IMAGE_ERROR';
