
export const SERVER_EXPIRES_TOKEN = 'SERVER_EXPIRES_TOKEN';

export const PENDING_LOGOUT_TIMER_STARTS = 'PENDING_LOGOUT_TIMER_STARTS';

export const PENDING_LOGOUT_TIMER_EXPIRES = 'PENDING_LOGOUT_TIMER_EXPIRES';

export const PENDING_LOGOUT_TIMER_TICKS = 'PENDING_LOGOUT_TIMER_TICKS';