export const USER_GET_PENDING_PRODUCTS = 'USER_GET_PENDING_PRODUCTS';
export const SERVER_GET_PENDING_PRODUCTS_SUCCESS = 'SERVER_GET_PENDING_PRODUCTS_SUCCESS';
export const SERVER_GET_PENDING_PRODUCTS_ERROR = 'SERVER_GET_PENDING_PRODUCTS_ERROR';

export const USER_GET_STORES = 'USER_GET_STORES';
export const SERVER_GET_STORES_SUCCESS = 'SERVER_GET_STORES_SUCCESS';
export const SERVER_GET_STORES_ERROR = 'SERVER_GET_STORES_ERROR';

export const USER_GET_BRANDS = 'USER_GET_BRANDS';
export const SERVER_GET_BRANDS_SUCCESS = 'SERVER_GET_BRANDS_SUCCESS';
export const SERVER_GET_BRANDS_ERROR = 'SERVER_GET_BRANDS_ERROR';

