export const USER_GET_PRODUCTS = 'USER_GET_PRODUCTS';
export const SERVER_GET_PRODUCTS_SUCCESS = 'SERVER_GET_PRODUCTS_SUCCESS';
export const SERVER_GET_PRODUCTS_ERROR = 'SERVER_GET_PRODUCTS_ERROR';

export const USER_GET_PRODUCTS_BRANDS = 'USER_GET_PRODUCTS_BRANDS';
export const SERVER_GET_PRODUCTS_BRANDS_SUCCESS = 'SERVER_GET_PRODUCTS_BRANDS_SUCCESS';
export const SERVER_GET_PRODUCTS_BRANDS_ERROR = 'SERVER_GET_PRODUCTS_BRANDS_ERROR';

export const USER_GET_PRODUCTS_TAGS = 'USER_GET_PRODUCTS_TAGS';
export const SERVER_GET_PRODUCTS_TAGS_SUCCESS = 'SERVER_GET_PRODUCTS_TAGS_SUCCESS';
export const SERVER_GET_PRODUCTS_TAGS_ERROR = 'SERVER_GET_PRODUCTS_TAGS_ERROR';

export const USER_GET_PRODUCTS_LAST_EDITORS = 'USER_GET_PRODUCTS_LAST_EDITORS';
export const SERVER_GET_PRODUCTS_LAST_EDITORS_SUCCESS = 'SERVER_GET_PRODUCTS_LAST_EDITORS_SUCCESS';
export const SERVER_GET_PRODUCTS_LAST_EDITORS_ERROR = 'SERVER_GET_PRODUCTS_LAST_EDITORS_ERROR';