export const USER_GET_SORT_BYS = 'USER_GET_SORT_BYS';

export const SERVER_GET_SORT_BYS_SUCCESS = 'SERVER_GET_SORT_BYS_SUCCESS';

export const SERVER_GET_SORT_BYS_ERROR = 'SERVER_GET_SORT_BYS_ERROR';